<?php

namespace app\components\router;

class RouteCacheDumper
{
	private function dump(array $routes): string
	{
		$export = var_export($routes, true);

		return <<<PHP
<?php

// Autogenerated route cache file.

return {$export};

PHP;
	}

	public function saveToFile(string $path, array $routes): void
	{
		file_put_contents($path, $this->dump($routes));
	}
}