<?php

namespace app\enum\LandPlot;

use app\enum\AbstractEnum;

class LandPlotTypePermittedUseEnum extends AbstractEnum
{
	public const AGRICULTURAL_USE = 1;
	public const CROP_PRODUCTION = 2;
	public const GRAIN_CULTIVATION_AND_OTHER_CROPS = 3;
	public const VEGETABLE_GROWING = 4;
	public const TONIC_MEDICINAL_AND_FLOWER_CULTIVATION = 5;
	public const GARDENING = 6;
	public const VITICULTURE = 7;
	public const FLAX_AND_HEMP_CULTIVATION = 8;
	public const ANIMAL_HUSBANDRY = 9;
	public const CATTLE_BREEDING = 10;
	public const FUR_FARMING = 11;
	public const POULTRY_FARMING = 12;
	public const PIG_FARMING = 13;
	public const BEEKEEPING = 14;
	public const FISH_FARMING = 15;
	public const AGRICULTURE_SCIENTIFIC_SUPPORT = 16;
	public const STORAGE_AND_PROCESS_AGRICULTURAL_PRODUCTS = 17;
	public const MAINTAINING_SUBSIDIARY_FARM_IN_FIELD = 18;
	public const NURSERIES = 19;
	public const ENSURING_AGRICULTURAL_PRODUCTION = 20;
	public const HAYMAKING = 21;
	public const GRAZING_FARM_ANIMALS = 22;
	public const RESIDENTIAL_DEVELOPMENT = 23;
	public const INDIVIDUAL_HOUSING_CONSTRUCTION = 24;
	public const LOW_RISE_MULTI_FLAT_RESIDENT_DEVELOPMENT = 25;
	public const SUBSIDIARY_FARMING_HOUSEHOLD_LAND_PLOT = 26;
	public const BLOCKED_RESIDENTIAL_DEVELOPMENT = 27;
	public const MOBILE_HOUSING = 28;
	public const MEDIUM_RISE_RESIDENTIAL_BUILDINGS = 29;
	public const MULTI_RISE_OR_HIGH_RISE_BUILDINGS = 30;
	public const MAINTENANCE_RESIDENTIAL_BUILDINGS = 31;
	public const VEHICLE_STORAGE = 32;
	public const PARKING_GARAGES_PERSONAL_USAGE = 33;
	public const PUBLIC_USE_CAPITAL_CONSTRUCTION = 34;
	public const UTILITY_SERVICES = 35;
	public const PROVISION_PUBLIC_SERVICES = 36;
	public const ADMINISTRATIVE_ORGANIZATIONS_PROVIDING_PUBLIC_SERVICES = 37;
	public const SOCIAL_SERVICES = 38;
	public const SOCIAL_SERVICE_HOMES = 39;
	public const PROVIDING_SOCIAL_ASSISTANCE_FOR_POPULATION = 40;
	public const PROVISION_COMMUNICATION_SERVICES = 41;
	public const DORMITORIES = 42;
	public const CONSUMER_SERVICES = 43;
	public const HEALTHCARE = 44;
	public const OUTPATIENT_CLINIC_SERVICES = 45;
	public const INPATIENT_MEDICAL_CARE = 46;
	public const SPECIAL_MEDICAL_ORGANIZATIONS = 47;
	public const EDUCATION_AND_ENLIGHTENMENT = 48;
	public const PRE_SCHOOL_PRIMARY_AND_SECONDARY_EDUCATION = 49;
	public const SECONDARY_AND_HIGHER_PROF_EDUCATION = 50;
	public const CULTURAL_DEVELOPMENT = 51;
	public const CULTURAL_OBJECTS_AND_LEISURE_ACTIVITIES = 52;
	public const CULTURE_PARKS_AND_RECREATION = 53;
	public const CIRCUSES_AND_MENAGERIES = 54;
	public const RELIGIOUS_USAGE = 55;
	public const IMPLEMENT_RELIGIOUS_RITES = 56;
	public const RELIGIOUS_GOVERNANCE_AND_EDUCATION = 57;
	public const PUBLIC_ADMINISTRATION = 58;
	public const STATE_ADMINISTRATION = 59;
	public const REPRESENTATIVE_ACTIVITIES = 60;
	public const PROVISION_SCIENTIFIC_ACTIVITIES = 61;
	public const PROVISION_ACTIVITIES_IN_HYDROMETEOROLOGY = 62;
	public const CONDUCTING_SCIENTIFIC_RESEARCH = 63;
	public const CONDUCTING_SCIENTIFIC_TESTS = 64;
	public const VETERINARY_SERVICES = 65;
	public const OUTPATIENT_VETERINARY_CARE = 66;
	public const ANIMAL_SHELTERS = 67;
	public const ENTREPRENEURSHIP = 68;
	public const BUSINESS_MANAGEMENT = 69;
	public const TRADE_FACILITIES = 70;
	public const MARKETS = 71;
	public const SHOPS = 72;
	public const BANKING_AND_INSURANCE_ACTIVITIES = 73;
	public const PUBLIC_CATERING = 74;
	public const HOTEL_SERVICE = 75;
	public const ENTERTAINMENT = 76;
	public const ENTERTAINMENT_EVENTS = 77;
	public const CONDUCTING_GAMBLING = 78;
	public const CONDUCTING_IN_GAMBLING_ZONES = 79;
	public const SERVICE_GARAGES = 80;
	public const ROAD_SERVICE_FACILITIES = 81;
	public const REFUELING_VEHICLES = 82;
	public const PROVIDING_ROAD_RECREATION = 83;
	public const CAR_WASHES = 84;
	public const CAR_REPAIR = 85;
	public const PARKING_OF_VEHICLES = 86;
	public const EXHIBITION_AND_FAIR_ACTIVITIES = 87;
	public const RECREATION_RECREATION = 88;
	public const SPORTS = 89;
	public const SPORTS_PROVISION_AND_ENTERTAINMENT_EVENTS = 90;
	public const PROVISION_INDOOR_SPORTS_ACTIVITIES = 91;
	public const SPORTS_GROUNDS = 92;
	public const EQUIPPED_PLAYGROUNDS_SPORTS_ACTIVITIES = 93;
	public const WATER_SPORTS = 94;
	public const AVIATION_SPORTS = 95;


	public static function labels(): array
	{
		return [
			self::AGRICULTURAL_USE => 'Сельскохозяйственное использование',
			self::CROP_PRODUCTION => 'Растениеводство',
			self::GRAIN_CULTIVATION_AND_OTHER_CROPS => 'Выращивание зерновых и иных сельскохозяйственных культур',
			self::VEGETABLE_GROWING => 'Овощеводство',
			self::TONIC_MEDICINAL_AND_FLOWER_CULTIVATION => 'Выращивание тонизирующих, лекарственных, цветочных культур',
			self::GARDENING => 'Садоводство',
			self::VITICULTURE => 'Виноградарство',
			self::FLAX_AND_HEMP_CULTIVATION => 'Выращивание льна и конопли',
			self::ANIMAL_HUSBANDRY => 'Животноводство',
			self::CATTLE_BREEDING => 'Скотоводство',
			self::FUR_FARMING => 'Звероводство',
			self::POULTRY_FARMING => 'Птицеводство',
			self::PIG_FARMING => 'Свиноводство',
			self::BEEKEEPING => 'Пчеловодство',
			self::FISH_FARMING => 'Рыбоводство',
			self::AGRICULTURE_SCIENTIFIC_SUPPORT => 'Научное обеспечение сельского хозяйства',
			self::STORAGE_AND_PROCESS_AGRICULTURAL_PRODUCTS => 'Хранение и переработка сельскохозяйственной продукции',
			self::MAINTAINING_SUBSIDIARY_FARM_IN_FIELD => 'Ведение личного подсобного хозяйства на полевых участках',
			self::NURSERIES => 'Питомники',
			self::ENSURING_AGRICULTURAL_PRODUCTION => 'Обеспечение сельскохозяйственного производства',
			self::HAYMAKING => 'Сенокошение',
			self::GRAZING_FARM_ANIMALS => 'Выпас сельскохозяйственных животных',
			self::RESIDENTIAL_DEVELOPMENT => 'Жилая застройка',
			self::INDIVIDUAL_HOUSING_CONSTRUCTION => 'Для индивидуального жилищного строительства',
			self::LOW_RISE_MULTI_FLAT_RESIDENT_DEVELOPMENT => 'Малоэтажная многоквартирная жилая застройка',
			self::SUBSIDIARY_FARMING_HOUSEHOLD_LAND_PLOT => 'Для ведения личного подсобного хозяйства (приусадебный земельный участок)',
			self::BLOCKED_RESIDENTIAL_DEVELOPMENT => 'Блокированная жилая застройка',
			self::MOBILE_HOUSING => 'Передвижное жилье',
			self::MEDIUM_RISE_RESIDENTIAL_BUILDINGS => 'Среднеэтажная жилая застройка',
			self::MULTI_RISE_OR_HIGH_RISE_BUILDINGS => 'Многоэтажная жилая застройка (высотная застройка)',
			self::MAINTENANCE_RESIDENTIAL_BUILDINGS => 'Обслуживание жилой застройки',
			self::VEHICLE_STORAGE => 'Хранение автотранспорта',
			self::PARKING_GARAGES_PERSONAL_USAGE => 'Размещение гаражей для собственных нужд',
			self::PUBLIC_USE_CAPITAL_CONSTRUCTION => 'Общественное использование объектов капитального строительства',
			self::UTILITY_SERVICES => 'Коммунальное обслуживание',
			self::PROVISION_PUBLIC_SERVICES => 'Предоставление коммунальных услуг',
			self::ADMINISTRATIVE_ORGANIZATIONS_PROVIDING_PUBLIC_SERVICES => 'Административные здания организаций, обеспечивающих предоставление коммунальных услуг',
			self::SOCIAL_SERVICES => 'Социальное обслуживание',
			self::SOCIAL_SERVICE_HOMES => 'Дома социального обслуживания',
			self::PROVIDING_SOCIAL_ASSISTANCE_FOR_POPULATION => 'Оказание социальной помощи населению',
			self::PROVISION_COMMUNICATION_SERVICES => 'Оказание услуг связи',
			self::DORMITORIES => 'Общежития',
			self::CONSUMER_SERVICES => 'Бытовое обслуживание',
			self::HEALTHCARE => 'Здравоохранение',
			self::OUTPATIENT_CLINIC_SERVICES => 'Амбулаторно-поликлиническое обслуживание',
			self::INPATIENT_MEDICAL_CARE => 'Стационарное медицинское обслуживание',
			self::SPECIAL_MEDICAL_ORGANIZATIONS => 'Медицинские организации особого назначения',
			self::EDUCATION_AND_ENLIGHTENMENT => 'Образование и просвещение',
			self::PRE_SCHOOL_PRIMARY_AND_SECONDARY_EDUCATION => 'Дошкольное, начальное и среднее общее образование',
			self::SECONDARY_AND_HIGHER_PROF_EDUCATION => 'Среднее и высшее профессиональное образование',
			self::CULTURAL_DEVELOPMENT => 'Культурное развитие',
			self::CULTURAL_OBJECTS_AND_LEISURE_ACTIVITIES => 'Объекты культурно-досуговой деятельности',
			self::CULTURE_PARKS_AND_RECREATION => 'Парки культуры и отдыха',
			self::CIRCUSES_AND_MENAGERIES => 'Цирки и зверинцы',
			self::RELIGIOUS_USAGE => 'Религиозное использование',
			self::IMPLEMENT_RELIGIOUS_RITES => 'Осуществление религиозных обрядов',
			self::RELIGIOUS_GOVERNANCE_AND_EDUCATION => 'Религиозное управление и образование',
			self::PUBLIC_ADMINISTRATION => 'Общественное управление',
			self::STATE_ADMINISTRATION => 'Государственное управление',
			self::REPRESENTATIVE_ACTIVITIES => 'Представительская деятельность',
			self::PROVISION_SCIENTIFIC_ACTIVITIES => 'Обеспечение научной деятельности',
			self::PROVISION_ACTIVITIES_IN_HYDROMETEOROLOGY => 'Обеспечение деятельности в области гидрометеорологии и смежных с ней областях',
			self::CONDUCTING_SCIENTIFIC_RESEARCH => 'Проведение научных исследований',
			self::CONDUCTING_SCIENTIFIC_TESTS => 'Проведение научных испытаний',
			self::VETERINARY_SERVICES => 'Ветеринарное обслуживание',
			self::OUTPATIENT_VETERINARY_CARE => 'Амбулаторное ветеринарное обслуживание',
			self::ANIMAL_SHELTERS => 'Приюты для животных',
			self::ENTREPRENEURSHIP => 'Предпринимательство',
			self::BUSINESS_MANAGEMENT => 'Деловое управление',
			self::TRADE_FACILITIES => 'Объекты торговли (торговые центры, торгово-развлекательные центры (комплексы))',
			self::MARKETS => 'Рынки',
			self::SHOPS => 'Магазины',
			self::BANKING_AND_INSURANCE_ACTIVITIES => 'Банковская и страховая деятельность',
			self::PUBLIC_CATERING => 'Общественное питание',
			self::HOTEL_SERVICE => 'Гостиничное обслуживание',
			self::ENTERTAINMENT => 'Развлечение',
			self::ENTERTAINMENT_EVENTS => 'Развлекательные мероприятия',
			self::CONDUCTING_GAMBLING => 'Проведение азартных игр',
			self::CONDUCTING_IN_GAMBLING_ZONES => 'Проведение азартных игр в игорных зонах',
			self::SERVICE_GARAGES => 'Служебные гаражи',
			self::ROAD_SERVICE_FACILITIES => 'Объекты дорожного сервиса',
			self::REFUELING_VEHICLES => 'Заправка транспортных средств',
			self::PROVIDING_ROAD_RECREATION => 'Обеспечение дорожного отдыха',
			self::CAR_WASHES => 'Автомобильные мойки',
			self::CAR_REPAIR => 'Ремонт автомобилей',
			self::PARKING_OF_VEHICLES => 'Стоянка транспортных средств',
			self::EXHIBITION_AND_FAIR_ACTIVITIES => 'Выставочно-ярмарочная деятельность',
			self::RECREATION_RECREATION => 'Отдых (рекреация)',
			self::SPORTS => 'Спорт',
			self::SPORTS_PROVISION_AND_ENTERTAINMENT_EVENTS => 'Обеспечение спортивно-зрелищных мероприятий',
			self::PROVISION_INDOOR_SPORTS_ACTIVITIES => 'Обеспечение занятий спортом в помещениях',
			self::SPORTS_GROUNDS => 'Площадки для занятий спортом',
			self::EQUIPPED_PLAYGROUNDS_SPORTS_ACTIVITIES => 'Оборудованные площадки для занятий спортом',
			self::WATER_SPORTS => 'Водный спорт',
			self::AVIATION_SPORTS => 'Авиационный спорт',
		];
	}
}