<?php

// Autogenerated route cache file.

return array (
  0 => 
  array (
    'class' => 'yii\\rest\\UrlRule',
    'controller' => 'companygroup',
    'pluralize' => true,
  ),
  1 => 
  array (
    'class' => 'yii\\rest\\UrlRule',
    'controller' => 'calendar',
    'pluralize' => true,
  ),
  2 => 
  array (
    'class' => 'yii\\rest\\UrlRule',
    'controller' => 'favorite-offer',
    'pluralize' => true,
  ),
  3 => 
  array (
    'class' => 'yii\\rest\\UrlRule',
    'controller' => 'company-events-log',
    'pluralize' => false,
  ),
  4 => 
  array (
    'class' => 'yii\\rest\\UrlRule',
    'controller' => 
    array (
      'chat-member-message-tags' => 'ChatMember/chat-member-message-tag',
    ),
    'pluralize' => true,
    'extraPatterns' => 
    array (
      'POST,OPTIONS' => 'create',
      'GET,OPTIONS' => 'index',
      'PUT,OPTIONS <id>' => 'update',
      'DELETE,OPTIONS <id>' => 'delete',
      'GET,OPTIONS <id>' => 'view',
    ),
  ),
  5 => 
  array (
    'class' => 'yii\\rest\\UrlRule',
    'controller' => 'call',
    'pluralize' => true,
    'extraPatterns' => 
    array (
      'POST,OPTIONS' => 'create',
      'GET,OPTIONS' => 'index',
      'PUT,OPTIONS <id>' => 'update',
      'DELETE,OPTIONS <id>' => 'delete',
      'GET,OPTIONS <id>' => 'view',
    ),
  ),
  6 => 
  array (
    'class' => 'yii\\rest\\UrlRule',
    'controller' => 'field',
    'pluralize' => true,
    'extraPatterns' => 
    array (
      'POST,OPTIONS' => 'create',
      'GET,OPTIONS' => 'index',
      'PUT,OPTIONS <id>' => 'update',
      'DELETE,OPTIONS <id>' => 'delete',
      'GET,OPTIONS <id>' => 'view',
    ),
  ),
  7 => 
  array (
    'class' => 'yii\\rest\\UrlRule',
    'controller' => 'effect',
    'pluralize' => true,
    'extraPatterns' => 
    array (
      'POST,OPTIONS' => 'create',
      'GET,OPTIONS' => 'index',
      'PUT,OPTIONS <id>' => 'update',
      'DELETE,OPTIONS <id>' => 'delete',
      'GET,OPTIONS <id>' => 'view',
    ),
  ),
  8 => 
  array (
    'class' => 'yii\\rest\\UrlRule',
    'controller' => 'survey-question-answer',
    'pluralize' => true,
    'extraPatterns' => 
    array (
      'POST,OPTIONS' => 'create',
      'GET,OPTIONS' => 'index',
      'PUT,OPTIONS <id>' => 'update',
      'DELETE,OPTIONS <id>' => 'delete',
      'GET,OPTIONS <id>' => 'view',
    ),
  ),
  9 => 
  array (
    'class' => 'yii\\rest\\UrlRule',
    'controller' => 'site',
    'pluralize' => true,
  ),
  10 => 
  array (
    'class' => 'yii\\rest\\UrlRule',
    'controller' => 'user',
    'pluralize' => true,
    'extraPatterns' => 
    array (
      'GET,OPTIONS' => 'index',
      'GET,OPTIONS online' => 'online',
      'POST,OPTIONS' => 'create',
      'POST,OPTIONS login' => 'login',
      'POST,OPTIONS logout' => 'logout',
      'POST,OPTIONS activity' => 'activity',
      'POST,OPTIONS change-password' => 'change-password',
      'GET,OPTIONS <id>' => 'view',
      'GET,OPTIONS <id>/sessions' => 'sessions',
      'POST,OPTIONS <id>/archive' => 'archive',
      'POST,OPTIONS <id>/restore' => 'restore',
      'PUT,OPTIONS <id>' => 'update',
      'DELETE,OPTIONS <id>' => 'delete-sessions',
      'DELETE,OPTIONS <id>/sessions' => 'delete-sessions',
    ),
  ),
  11 => 
  array (
    'class' => 'yii\\rest\\UrlRule',
    'controller' => 'session',
    'pluralize' => true,
    'extraPatterns' => 
    array (
      'GET,OPTIONS' => 'index',
      'DELETE,OPTIONS <id>' => 'delete',
    ),
  ),
  12 => 
  array (
    'class' => 'yii\\rest\\UrlRule',
    'controller' => 
    array (
      'companies' => 'company',
    ),
    'pluralize' => true,
    'extraPatterns' => 
    array (
      'GET,OPTIONS' => 'index',
      'GET,OPTIONS product-range-list' => 'product-range-list',
      'GET,OPTIONS in-the-bank-list' => 'in-the-bank-list',
      'POST,OPTIONS' => 'create',
      'GET,OPTIONS <id>' => 'view',
      'GET,OPTIONS <id>/status-history' => 'view-status-history',
      'PUT,OPTIONS <id>' => 'update',
      'POST,OPTIONS <id>/enable' => 'enable',
      'POST,OPTIONS <id>/delete' => 'delete',
      'POST,OPTIONS <id>/passive' => 'passive',
      'POST,OPTIONS <id>/link-message' => 'link-message',
      'POST,OPTIONS <id>/create-note' => 'create-note',
      'POST,OPTIONS <id>/change-consultant' => 'change-consultant',
      'POST,OPTIONS <id>/logo' => 'update-logo',
      'DELETE,OPTIONS <id>/logo' => 'delete-logo',
      'DELETE,OPTIONS <id>' => 'delete',
    ),
  ),
  13 => 
  array (
    'class' => 'yii\\rest\\UrlRule',
    'controller' => 'entity-message-link',
    'pluralize' => true,
    'extraPatterns' => 
    array (
      'GET,OPTIONS' => '/',
      'DELETE,OPTIONS <id>' => 'delete',
    ),
  ),
  14 => 
  array (
    'class' => 'yii\\rest\\UrlRule',
    'controller' => 'request',
    'pluralize' => true,
    'extraPatterns' => 
    array (
      'GET,OPTIONS' => 'index',
      'GET,OPTIONS company-requests/<id>' => 'company-requests',
      'POST,OPTIONS' => 'create',
      'PATCH,OPTIONS disable/<id>' => 'disable',
      'PATCH,OPTIONS undisable/<id>' => 'undisable',
      'GET,OPTIONS <id>' => 'view',
      'POST,OPTIONS <id>/clone' => 'clone',
      'POST,OPTIONS <id>/change-consultant' => 'change-consultant',
      'PUT,OPTIONS <id>' => 'update',
    ),
  ),
  15 => 
  array (
    'class' => 'yii\\rest\\UrlRule',
    'controller' => 'contact',
    'pluralize' => true,
    'extraPatterns' => 
    array (
      'GET,OPTIONS' => 'index',
      'GET,OPTIONS company-contacts/<id>' => 'company-contacts',
      'POST,OPTIONS' => 'create',
      'POST,OPTIONS create-comment' => 'create-comment',
      'GET,OPTIONS <id>' => 'view',
      'GET,OPTIONS <id>/phones' => 'view-phones',
      'PUT,OPTIONS <id>' => 'update',
      'POST,OPTIONS <id>/disable' => 'disable',
      'POST,OPTIONS <id>/enable' => 'enable',
      'POST,OPTIONS <id>/transfer-to-company' => 'transfer-to-company',
      'POST,OPTIONS <id>/phones' => 'create-phone',
    ),
  ),
  16 => 
  array (
    'class' => 'yii\\rest\\UrlRule',
    'controller' => 'phone',
    'pluralize' => true,
    'extraPatterns' => 
    array (
      'GET,OPTIONS' => 'index',
      'PUT,OPTIONS <id>' => 'update',
      'POST,OPTIONS <id>/disable' => 'disable',
      'POST,OPTIONS <id>/enable' => 'enable',
      'POST,OPTIONS <id>/mark-as-main' => 'mark-as-main',
      'DELETE,OPTIONS <id>' => 'delete',
    ),
  ),
  17 => 
  array (
    'class' => 'yii\\rest\\UrlRule',
    'controller' => 'contact-comment',
    'pluralize' => true,
    'extraPatterns' => 
    array (
      'PUT,OPTIONS <id>' => 'update',
      'DELETE,OPTIONS <id>' => 'delete',
    ),
  ),
  18 => 
  array (
    'class' => 'yii\\rest\\UrlRule',
    'controller' => 'contact-position',
    'pluralize' => true,
    'extraPatterns' => 
    array (
      'GET,OPTIONS' => 'index',
      'POST,OPTIONS' => 'create',
      'PUT,OPTIONS <id>' => 'update',
      'DELETE,OPTIONS <id>' => 'delete',
    ),
  ),
  19 => 
  array (
    'class' => 'yii\\rest\\UrlRule',
    'controller' => 'timeline',
    'pluralize' => false,
    'extraPatterns' => 
    array (
      'GET,OPTIONS' => 'index',
      'GET,OPTIONS search' => 'search',
      'GET,OPTIONS <id>' => 'view',
      'GET,OPTIONS action-comments/<id>' => 'action-comments',
      'POST,OPTIONS' => 'create',
      'POST,OPTIONS action-comment' => 'add-action-comment',
      'PATCH,OPTIONS update-step/<id>' => 'update-step',
    ),
  ),
  20 => 
  array (
    'class' => 'yii\\rest\\UrlRule',
    'controller' => 'notification',
    'pluralize' => true,
    'extraPatterns' => 
    array (
      'GET,OPTIONS' => 'index',
      'GET,OPTIONS <id>/viewed-not-count' => 'viewed-not-count',
      'GET,OPTIONS <id>/viewed-all' => 'viewed-all',
      'GET,OPTIONS <id>/count' => 'count',
    ),
  ),
  21 => 
  array (
    'class' => 'yii\\rest\\UrlRule',
    'controller' => 'calllist',
    'pluralize' => true,
    'extraPatterns' => 
    array (
      'GET,OPTIONS' => 'index',
      'GET,OPTIONS <caller_id>/viewed-not-count' => 'viewed-not-count',
      'GET,OPTIONS <caller_id>/viewed-all' => 'viewed-all',
      'GET,OPTIONS <caller_id>/count' => 'count',
    ),
  ),
  22 => 
  array (
    'class' => 'yii\\rest\\UrlRule',
    'controller' => 'oldDb/object',
    'pluralize' => true,
    'extraPatterns' => 
    array (
      'GET,OPTIONS' => 'index',
      'GET,OPTIONS offers' => 'offers',
      'GET,OPTIONS offers-map' => 'offers-map',
      'GET,OPTIONS offers-count' => 'offers-count',
      'GET,OPTIONS offers-map-count' => 'offers-map-count',
      'POST,OPTIONS toggle-avito-ad/<originalId>' => 'toggle-avito-ad',
      'POST,OPTIONS toggle-is-fake/<originalId>' => 'toggle-is-fake',
    ),
  ),
  23 => 
  array (
    'class' => 'yii\\rest\\UrlRule',
    'controller' => 'oldDb/location',
    'pluralize' => true,
    'extraPatterns' => 
    array (
      'GET,OPTIONS region-list' => 'region-list',
    ),
  ),
  24 => 
  array (
    'class' => 'yii\\rest\\UrlRule',
    'controller' => 'pdf/presentation',
    'pluralize' => true,
    'extraPatterns' => 
    array (
      'GET html' => 'html',
    ),
  ),
  25 => 
  array (
    'class' => 'yii\\rest\\UrlRule',
    'controller' => 'complex',
    'pluralize' => false,
    'extraPatterns' => 
    array (
      'GET,OPTIONS <id>' => 'view',
    ),
  ),
  26 => 
  array (
    'class' => 'yii\\rest\\UrlRule',
    'controller' => 'letter',
    'pluralize' => true,
    'extraPatterns' => 
    array (
      'POST,OPTIONS send-custom-letter' => 'send-custom-letter',
      'POST,OPTIONS send' => 'send',
    ),
  ),
  27 => 
  array (
    'class' => 'yii\\rest\\UrlRule',
    'controller' => 'letter-contact-answer',
    'pluralize' => true,
    'extraPatterns' => 
    array (
      'POST,OPTIONS' => 'create',
    ),
  ),
  28 => 
  array (
    'class' => 'yii\\rest\\UrlRule',
    'controller' => 'archiver',
    'pluralize' => false,
    'extraPatterns' => 
    array (
      'GET,OPTIONS download' => 'download',
    ),
  ),
  29 => 
  array (
    'class' => 'yii\\rest\\UrlRule',
    'controller' => 
    array (
      'chat-members' => 'ChatMember/chat-member',
    ),
    'pluralize' => true,
    'extraPatterns' => 
    array (
      'GET,OPTIONS' => 'index',
      'GET,OPTIONS statistic' => 'statistic',
      'POST,OPTIONS pin-message' => 'pin-message',
      'POST,OPTIONS unpin-message' => 'unpin-message',
      'GET,OPTIONS <id>' => 'view',
      'GET,OPTIONS <id>/pinned-message' => 'pinned-message',
      'GET,OPTIONS <id>/media' => 'media',
      'POST,OPTIONS <id>/called' => 'called',
    ),
  ),
  30 => 
  array (
    'class' => 'yii\\rest\\UrlRule',
    'controller' => 
    array (
      'chat-member-messages' => 'ChatMember/chat-member-message',
    ),
    'pluralize' => true,
    'extraPatterns' => 
    array (
      'GET,OPTIONS' => 'index',
      'GET,OPTIONS search' => 'search',
      'POST,OPTIONS' => 'create',
      'POST,OPTIONS with-task' => 'create-with-task',
      'POST,OPTIONS with-tasks' => 'create-with-tasks',
      'POST,OPTIONS create-task/<id>' => 'create-task',
      'POST,OPTIONS create-tasks/<id>' => 'create-tasks',
      'POST,OPTIONS create-alert/<id>' => 'create-alert',
      'POST,OPTIONS create-reminder/<id>' => 'create-reminder',
      'POST,OPTIONS create-notification/<id>' => 'create-notification',
      'POST,OPTIONS view-message/<id>' => 'view-message',
      'GET,OPTIONS <id>' => 'view',
      'PUT,OPTIONS <id>' => 'update',
      'DELETE,OPTIONS <id>' => 'delete',
    ),
  ),
  31 => 
  array (
    'class' => 'yii\\rest\\UrlRule',
    'controller' => 'media',
    'pluralize' => true,
    'extraPatterns' => 
    array (
      'GET,OPTIONS' => 'index',
      'GET,OPTIONS <id>' => 'view',
      'DELETE,OPTIONS <id>' => 'delete',
    ),
  ),
  32 => 
  array (
    'class' => 'yii\\rest\\UrlRule',
    'controller' => 'survey',
    'pluralize' => true,
    'extraPatterns' => 
    array (
      'GET,OPTIONS' => 'index',
      'POST,OPTIONS' => 'create',
      'GET,OPTIONS pending-by-chat-member/<id>' => 'view-pending-by-chat-member-id',
      'GET,OPTIONS statistics' => 'statistics',
      'GET,OPTIONS <id>' => 'view',
      'GET,OPTIONS <id>/with-questions' => 'view-with-questions',
      'POST,OPTIONS <id>/complete' => 'complete',
      'POST,OPTIONS <id>/cancel' => 'cancel',
      'POST,OPTIONS <id>/delay' => 'delay',
      'POST,OPTIONS <id>/continue' => 'continue',
      'POST,OPTIONS <id>/change-comment' => 'change-comment',
      'POST,OPTIONS <id>/actions' => 'create-action',
      'PUT,OPTIONS <id>' => 'update',
      'PUT,OPTIONS <id>/with-survey-question-answer' => 'update-with-survey-question-answer',
      'DELETE,OPTIONS <id>' => 'delete',
    ),
  ),
  33 => 
  array (
    'class' => 'yii\\rest\\UrlRule',
    'controller' => 'survey-action',
    'pluralize' => true,
    'extraPatterns' => 
    array (
      'PUT,OPTIONS <id>' => 'update',
    ),
  ),
  34 => 
  array (
    'class' => 'yii\\rest\\UrlRule',
    'controller' => 'question',
    'pluralize' => true,
    'extraPatterns' => 
    array (
      'GET,OPTIONS' => 'index',
      'GET,OPTIONS with-question-answer' => 'index-with-question-answer',
      'POST,OPTIONS' => 'create',
      'POST,OPTIONS with-question-answer' => 'create-with-question-answer',
      'GET,OPTIONS <id>' => 'view',
      'PUT,OPTIONS <id>' => 'update',
      'DELETE,OPTIONS <id>' => 'delete',
    ),
  ),
  35 => 
  array (
    'class' => 'yii\\rest\\UrlRule',
    'controller' => 'equipment',
    'pluralize' => true,
    'extraPatterns' => 
    array (
      'POST,OPTIONS' => 'create',
      'GET,OPTIONS' => 'index',
      'PUT,OPTIONS <id>' => 'update',
      'DELETE,OPTIONS <id>' => 'delete',
      'GET,OPTIONS <id>' => 'view',
      'POST,OPTIONS <id>/called' => 'called',
    ),
  ),
  36 => 
  array (
    'class' => 'yii\\rest\\UrlRule',
    'controller' => 'question-answer',
    'pluralize' => true,
    'extraPatterns' => 
    array (
      'GET,OPTIONS with-questions' => 'with-questions',
      'POST,OPTIONS' => 'create',
      'GET,OPTIONS' => 'index',
      'PUT,OPTIONS <id>' => 'update',
      'DELETE,OPTIONS <id>' => 'delete',
      'GET,OPTIONS <id>' => 'view',
    ),
  ),
  37 => 
  array (
    'class' => 'yii\\rest\\UrlRule',
    'controller' => 'task',
    'pluralize' => true,
    'extraPatterns' => 
    array (
      'GET,OPTIONS' => 'index',
      'GET,OPTIONS counts' => 'counts',
      'GET,OPTIONS relations-statistics' => 'relations-statistics',
      'GET,OPTIONS statistic' => 'statistic',
      'POST,OPTIONS' => 'create',
      'POST,OPTIONS for-users' => 'create-for-users',
      'POST,OPTIONS change-status/<id>' => 'change-status',
      'GET,OPTIONS <id>' => 'view',
      'PUT,OPTIONS <id>' => 'update',
      'DELETE,OPTIONS <id>' => 'delete',
      'GET,OPTIONS <id>/history' => 'history',
      'POST,OPTIONS <id>/read' => 'read',
      'POST,OPTIONS <id>/assign' => 'assign',
      'POST,OPTIONS <id>/postpone' => 'postpone',
      'POST,OPTIONS <id>/restore' => 'restore',
      'POST,OPTIONS <id>/change-dates' => 'change-dates',
      'POST,OPTIONS <id>/change-type' => 'change-type',
      'GET,OPTIONS <id>/relations' => 'relations',
      'POST,OPTIONS <id>/relations' => 'create-relations',
      'GET,OPTIONS <id>/files' => 'files',
      'POST,OPTIONS <id>/files' => 'create-files',
      'DELETE,OPTIONS <id>/files' => 'delete-files',
      'GET,OPTIONS <id>/comments' => 'comments',
      'POST,OPTIONS <id>/comments' => 'create-comment',
    ),
  ),
  38 => 
  array (
    'class' => 'yii\\rest\\UrlRule',
    'controller' => 'task-relation-entity',
    'pluralize' => false,
    'extraPatterns' => 
    array (
      'DELETE,OPTIONS <id>' => 'delete',
      'PUT,OPTIONS <id>' => 'update',
    ),
  ),
  39 => 
  array (
    'class' => 'yii\\rest\\UrlRule',
    'controller' => 'task-tag',
    'pluralize' => true,
    'extraPatterns' => 
    array (
      'GET,OPTIONS all' => 'all',
      'POST,OPTIONS' => 'create',
      'GET,OPTIONS' => 'index',
      'PUT,OPTIONS <id>' => 'update',
      'DELETE,OPTIONS <id>' => 'delete',
      'GET,OPTIONS <id>' => 'view',
    ),
  ),
  40 => 
  array (
    'class' => 'yii\\rest\\UrlRule',
    'controller' => 'task-comment',
    'pluralize' => true,
    'extraPatterns' => 
    array (
      'GET,OPTIONS' => 'index',
      'GET,OPTIONS <id>' => 'view',
      'PUT,OPTIONS <id>' => 'update',
      'DELETE,OPTIONS <id>' => 'delete',
    ),
  ),
  41 => 
  array (
    'class' => 'yii\\rest\\UrlRule',
    'controller' => 'task-favorite',
    'pluralize' => true,
    'extraPatterns' => 
    array (
      'GET,OPTIONS' => 'index',
      'POST,OPTIONS' => 'create',
      'DELETE,OPTIONS <id>' => 'delete',
      'POST,OPTIONS <id>/change-position' => 'change-position',
    ),
  ),
  42 => 
  array (
    'class' => 'yii\\rest\\UrlRule',
    'controller' => 'utilities',
    'pluralize' => false,
    'extraPatterns' => 
    array (
      'POST,OPTIONS fix-land-object-purposes' => 'fix-land-object-purposes',
      'POST,OPTIONS reassign-consultants-to-companies' => 'reassign-consultants-to-companies',
      'POST,OPTIONS transfer-companies-to-consultant/<id>' => 'transfer-companies-to-consultant',
    ),
  ),
  43 => 
  array (
    'class' => 'yii\\rest\\UrlRule',
    'controller' => 'folder',
    'pluralize' => true,
    'extraPatterns' => 
    array (
      'GET,OPTIONS' => 'index',
      'GET,OPTIONS entities' => 'entities',
      'POST,OPTIONS' => 'create',
      'POST,OPTIONS reorder' => 'reorder',
      'PUT,OPTIONS <id>' => 'update',
      'DELETE,OPTIONS <id>' => 'delete',
      'POST,OPTIONS <id>/entities' => 'add-entities',
      'POST,OPTIONS <id>/clear' => 'clear-entities',
      'DELETE,OPTIONS <id>/entities' => 'remove-entities',
    ),
  ),
  44 => 
  array (
    'class' => 'yii\\rest\\UrlRule',
    'controller' => 'user-tour',
    'pluralize' => true,
    'extraPatterns' => 
    array (
      'GET,OPTIONS history' => 'history',
      'GET,OPTIONS status' => 'status',
      'POST,OPTIONS viewed' => 'viewed',
      'POST,OPTIONS <id>/reset' => 'reset',
    ),
  ),
  45 => 
  array (
    'class' => 'yii\\rest\\UrlRule',
    'controller' => 'deal',
    'pluralize' => true,
    'extraPatterns' => 
    array (
      'GET,OPTIONS' => 'index',
      'POST,OPTIONS for-request/<id>' => 'create-for-request',
      'GET,OPTIONS <id>' => 'view',
      'PUT,OPTIONS <id>' => 'update',
      'DELETE,OPTIONS <id>' => 'delete',
    ),
  ),
  46 => 
  array (
    'class' => 'yii\\rest\\UrlRule',
    'controller' => 'message-template',
    'pluralize' => true,
    'extraPatterns' => 
    array (
      'GET,OPTIONS render/<template>' => 'render',
    ),
  ),
  47 => 
  array (
    'class' => 'yii\\rest\\UrlRule',
    'controller' => 'letter-tracking',
    'pluralize' => false,
    'extraPatterns' => 
    array (
      'GET,OPTIONS open/<letter_contact_id>' => 'open',
    ),
  ),
  48 => 
  array (
    'class' => 'yii\\rest\\UrlRule',
    'controller' => 'user-notification',
    'pluralize' => true,
    'extraPatterns' => 
    array (
      'GET,OPTIONS' => 'index',
      'GET,OPTIONS user/count' => 'count',
      'POST,OPTIONS user/acted-all' => 'acted-all',
      'POST,OPTIONS send' => 'send',
      'GET,OPTIONS <id>' => 'view',
      'POST,OPTIONS <id>/viewed' => 'viewed',
      'POST,OPTIONS <id>/acted' => 'acted',
      'POST,OPTIONS <id>/actions/<actionId>/process' => 'process-action',
    ),
  ),
  49 => 
  array (
    'class' => 'yii\\rest\\UrlRule',
    'controller' => 'user-notification-action-log',
    'pluralize' => true,
    'extraPatterns' => 
    array (
      'GET,OPTIONS' => 'index',
    ),
  ),
  50 => 
  array (
    'class' => 'yii\\rest\\UrlRule',
    'controller' => 'user-notification-template',
    'pluralize' => true,
    'extraPatterns' => 
    array (
      'GET,OPTIONS' => 'index',
      'POST,OPTIONS' => 'create',
      'GET,OPTIONS <id>' => 'view',
      'POST,OPTIONS <id>/disable' => 'disable',
      'POST,OPTIONS <id>/enable' => 'enable',
      'PUT,OPTIONS <id>' => 'update',
      'DELETE,OPTIONS <id>' => 'delete',
    ),
  ),
  51 => 
  array (
    'class' => 'yii\\rest\\UrlRule',
    'controller' => 'integration/telegram',
    'pluralize' => false,
    'extraPatterns' => 
    array (
      'POST,OPTIONS start' => 'start',
      'POST,OPTIONS status' => 'status',
      'POST,OPTIONS revoke' => 'revoke',
    ),
  ),
  52 => 
  array (
    'class' => 'yii\\rest\\UrlRule',
    'controller' => 
    array (
      'integration/telegram/admin' => 'integration/telegram-admin',
    ),
    'pluralize' => true,
    'extraPatterns' => 
    array (
      'GET,OPTIONS list' => 'list',
      'GET,OPTIONS tickets' => 'tickets',
      'POST,OPTIONS revoke-user/<id>' => 'revoke-user',
      'POST,OPTIONS revoke-link/<id>' => 'revoke-link',
    ),
  ),
  53 => 
  array (
    'class' => 'yii\\rest\\UrlRule',
    'controller' => 
    array (
      'integration/telegram/webhook' => 'integration/telegram-webhook',
    ),
    'pluralize' => true,
    'extraPatterns' => 
    array (
      'POST,OPTIONS' => 'handle',
    ),
  ),
  54 => 
  array (
    'class' => 'yii\\rest\\UrlRule',
    'controller' => 'integration/whatsapp',
    'pluralize' => false,
    'extraPatterns' => 
    array (
      'POST,OPTIONS link' => 'link',
      'POST,OPTIONS status' => 'status',
      'POST,OPTIONS revoke' => 'revoke',
    ),
  ),
  55 => 
  array (
    'class' => 'yii\\rest\\UrlRule',
    'controller' => 
    array (
      'integration/whatsapp/admin' => 'integration/whatsapp-admin',
    ),
    'pluralize' => true,
    'extraPatterns' => 
    array (
      'GET,OPTIONS list' => 'list',
      'POST,OPTIONS revoke-user/<id>' => 'revoke-user',
      'POST,OPTIONS revoke-link/<id>' => 'revoke-link',
    ),
  ),
  56 => 
  array (
    'class' => 'yii\\rest\\UrlRule',
    'controller' => 'complex-new',
    'pluralize' => false,
    'extraPatterns' => 
    array (
      'GET,OPTIONS <id>' => 'view',
    ),
  ),
);
