GET {{url}}/complex/54?
    expand=guardTypes,
           internetTypes,
           waterTypes,
           objects.company.consultant.userProfile,
           objects.objectClassRecord,
           objects.firefightingType,
           objects.location.regionRecord,
           objects.company.mainContact.phones,
           objects.company.mainContact.emails,
           location.regionRecord,
           location.highwayRecord,
           location.directionRecord,
           location.districtRecord,
           location.districtMoscowRecord,
           location.townRecord.townTypeRecord,
           location.townCentralRecord,
           location.metroRecord,
           location.districtTypeRecord,
           author.userProfile,
           agent.userProfile,
           objects.purposesRecords,
           objects.commercialOffers.dealTypeRecord,
           objects.commercialOffers.companyRecord.mainContact.phones,
           objects.commercialOffers.companyRecord.mainContact.emails,
           objects.floorsRecords.number,
           objects.floorsRecords.floorTypes,
           objects.cranes.controls,
           objects.cranes.state,
           objects.cranes.beam,
           objects.cranes.beamAmount,
           objects.cranes.hoisting,
           objects.cranes.location,
           objects.cranes.type,
           objects.commercialOffers.blocks.deal,
           objects.floorsRecords.parts.floorTypes,
           objects.elevatorsRecords.elevatorType,
           objects.commercialOffers.summaryBlock.partsRecords,
           objects.commercialOffers.consultant.userProfile,
           location.highwayRelevantRecords,
           location.townsRelevantRecords
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

###


GET {{url}}/complex/54?
    expand=objects.commercialOffers.summaryBlock.partsRecords,location.districtFormerRecord
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

###